quarkus:
  http:
    cors:
      ~: true
      access-control-allow-credentials: true
      headers: Access-Control-Allow-Origin, Content-Type, Authorization
      methods: GET, POST, PUT, DELETE, OPTIONS
      origins: "*"
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASS}
    jdbc:
      url: ${DB_URL}
      max-size: 16
  swagger-ui:
    always-include: true